### ISSUE TITLE
[XRLayer, OpenXR] Copy regualar texture to layer texture

### ISSUE THREAD

**Issue by eXponenta** [cabanier/WebXR-issues#2]
Copying to layer texture from regular GL texture by  `copyTexSubImage2D` in colorFormat = RGBA is failing with:

```
[.WebGL-0xc6704600]GL ERROR :GL_INVALID_OPERATION : glCopyTexSubImage2D: incompatible format
```

**Source:**
https://replit.com/@eXponenta/Oclus-OpenXR-BUG-CopyTexture#script.js

**Demo:**
https://Oclus-OpenXR-BUG-CopyTexture.exponenta.repl.co

**Note:**
OpenXR should be enabled in chrome://flags

**Upd:**
Fix should be shipped in browser version 22.1. Waiting public release.

**Comment by cabanier** [comment]
This was fixed in the private build, right?

**Comment by eXponenta** [comment]
Yep, for regular textures in RGBA/SRGB types, other wasn't checked.

**Comment by eXponenta** [comment]
Arrived in Oculus Browser 22.1
