### ISSUE TITLE
[OpenXR XRCubeLayer] Degradation. Cube layer down with internal error while upload 

### ISSUE THREAD

**Issue by eXponenta** [cabanier/WebXR-issues#3]
Reproduced on Oculus 1/2

Browser v22.1.0.2.42.378269191
System v41.0.113.268.376573602

Demo:
https://immersive-web.github.io/webxr-samples/layers-samples/cube-layer.html

Errors:
<img width="748" alt="image" src="https://user-images.githubusercontent.com/12572222/175784888-0f2546f2-fb3c-4248-928f-eef5a0696e64.png">

**Comment by cabanier** [comment]
Fixed in 23.x
